### ISSUE TITLE
Unable to view the file in a viewer

### ISSUE THREAD

**Issue by a-parida12** [rohithkumar31/pdf2dicom#1]
Hi,
I tried running your code and sample without any change, but the converted files not able to viewed in the weasis viewer or any viewer. My web viewer complains.
<img width="550" alt="Screenshot 2021-05-18 at 10 45 43" src="https://user-images.githubusercontent.com/23334003/118621554-c3201780-b7c6-11eb-8443-ffd052cc3902.png">

I tried with other dicompdf the viewer works fine. Can you help identify changes in the code?

**Comment by a-parida12** [comment]
It seems to be missing a `TransferSyntaxUID` in the dicom file meta info, added that and some conversion specific fields have been populated.

**Comment by rohithkumar31** [comment]
Thanks for the fix @a-parida12. Closing the issue.
