### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by cfhammill** [rohithkumar31/pdf2dicom#4]
Thanks for this @rohithkumar31, really useful to have an example of pdf encapsulation!

Would you consider adding a software license e.g. MIT to the repo so that others can use your code directly?

**Comment by rohithkumar31** [comment]
Thanks @cfhammill. I've added the license. Please leave a star if this has helped you.

**Comment by cfhammill** [comment]
Amazing, thanks @rohithkumar31!
