### ISSUE TITLE
Generate random uid alternative

### ISSUE THREAD

**Issue by Eschivo** [rohithkumar31/pdf2dicom#5]
Hi @rohithkumar31, is there a specific reason for the UID generation of the encapsulated dicom through the function `generate_random_uid` here?

https://github.com/rohithkumar31/pdf2dicom/blob/4bbbc0c618afd8e06886e361543d10e863561d9c/main.py#L5-L6

Because if that format isn't necessary or requested by the standard, I just found that the pydicom module implements a [`generate_uid`](https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.uid.generate_uid.html) function that could be used instead, resulting in a cleaner code.

If you think that this implementation could be valuable I can refactor the code soon. 

Best,
Elia

**Comment by rohithkumar31** [comment]
Hi @EliaSchiavon. The value should just be in a valid UID format as per DICOM standard. I wasn't aware of the `generate_uid` method in pydicom. Thanks for the nice suggestion. Please feel free to refactor the code if possible. Let me know if you cannot spend time on refactoring, I can also do it.

Thanks,
Rohith
